import os

JUPYTER_BYTE_LIMIT = 1 << 24
JUPYTER_WIDGETS_BYTE_LIMIT = 1 << 20

SCATTER_PLOT_SAMPLE_LIMIT = 10000
SCATTER_PLOT_LARGE_DATA_THRESHOLD = 50000
SMART_SAMPLE_MIN_SIZE = 1000

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
